apiVersion: v1
kind: Service
metadata:
  labels:
    component: api
  name: api-svc
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: api-svc
  selector:
    app: todo
    component: api
  type: ClusterIP
