apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    component: redis
    app: todo
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      component: redis
      app: todo
  template:
    metadata:
      labels:
        component: redis
        app: todo
    spec:
      containers:
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 100m
          args:
            - redis-server
            - --requirepass ccp2
            - --appendonly yes
